# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ursula
email: bcclaro+u@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  este site disponibiliza digitalmente o conteúdo integral do romance ursula (1859), de maria firmina dos reis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://odanoburu.github.io/ursula" # the base hostname & protocol for your site
github_username:  odanoburu


# Build settings
markdown: kramdown
encoding: UTF-8
